-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) AS 'count' FROM ANIMAL_INS WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog' GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE;

-- 동명 동물 수 찾
SELECT NAME, COUNT(*) AS 'COUNT' FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT > 1 ORDER BY NAME;기

-- 입영 시각 구하기(1)
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(*) FROM ANIMAL_OUTS GROUP BY HOUR HAVING 9<=HOUR AND HOUR<20 ORDER BY HOUR;