-- 01. 최대값 구하기
SELECT MAX(DATETIME) FROM ANIMAL_INS;

-- 02. 최솟값 구하기
SELECT MIN(DATETIME) FROM ANIMAL_INS;

-- 03. 동물의 수 구하기
SELECT COUNT(*) FROM ANIMAL_INS;

-- 04. 중복 제거하기
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL;